export const ar = () => {
  return {
    header: {
      faq: "التعليمات والمساعدة",
      connect: "الدخول",
      sub: "تسجيل",
      search: "بحث",
      lang: "العربية",
      setting: "الإعدادات",
      profil: "الملف الشخصي ",
      disconnect: "خروج",
    },
    Login: {
      errOccured: "حدث خطأ:",
      TitleConnect: "تسجيل الدخول",
      email: "البريد الإلكتروني",
      pass: " كلمة السر",
      passMissed: " نسيت رقمك السري ؟",
      btnConnect: "دخول",
      titleModalMissendPass: "أعد تعيين كلمة المرور الخاصة بك",
      emailSended: "تم ارسال البريد الالكتروني بنجاح",
      reset: "إعادة ضبط",
      emailNotFound: "هذا البريد الإلكتروني غير مسجل على موقعنا",
      errIncorrect: "بريد إلكتروني أو كلمة مرور غير صحيحة",
      errBlocked: "حسابك محظور",
      errWaiting: "تأكيد بريدك الإلكتروني! تم إرسال ارتباط إلى",
      errUnknow: "خطأ , يرجى المحاولة مرة أخرى",
      btnResend: "إعادة إرسال",
    },
    signup: {
      errOccured: "حدث خطأ:",
      TitleSign: "تسجيل",
      email: "عنوان البريد الإلكتروني",
      pass: "كلمة المرور (بحد أدنى 8 أحرف)",
      confirmPass: "تأكيد كلمة المرور",
      acceptLabel: "أقر بأنني قرأت وأوافق",
      conditionTerms: "شروط وأحكام المنصة",

      username: "اسم االمستخدم",
      lastname: "اللقب",
      firstname: "الاسم",
      passNotIdentique: "كلمات المرور غير متطابقة",
      resend: "إعادة الإرسال؟",
      errorShortName: "يجب أن يحتوي اسم المستخدم واسم العائلة والاسم الأول بين 2 و 30 حرفًا",
      errorEmailInvalide: "بريد إلكتروني غير صالح",
      passShort: "يجب أن تحتوي كلمة المرور على الأقل على: 8 أحرف , وحرف كبير واحد , وحرف صغير واحد ورقمان",
      infoExist: "معلومات اسم المستخدم / البريد الإلكتروني موجودة بالفعل",
      successEmailSended: " \n تم إرسال بريد إلكتروني إلى \n ",
    },
    profil: {
      title: "الملف الشخصي",
      general: "عام",
      security: "حماية",
      adress: "العنوان",
      contact: "اتصال",
    },
    profilGeneral: {
      title: "تحرير المعلومات الخاصة بك",
      username: "اسم االمستخدم",
      lastname: "اللقب",
      firstname: "الاسم",
      placeOlderNames: "بين 3 و 20 حرفًا بأحرف لاتينية",
      selectSexe: "الجنس",
      selectBoy: "ذكر",
      selectGirl: "أنثى",
      dateBirth: "تاريخ الميلاد",
      dateBDay: "اليوم",
      dateMounth: "الشهر",
      dateYear: "السنة",
      birth_place: "مكان الميلاد",
      PObirth_place: "المدينة ولاية",
      submitBtn: "إرسال",
    },
    profilSecurity: {
      title: "حماية",
      email: "بريد إلكتروني",
      pOemail: "example@gmail.com",
      submitBtn: "إرسال",
    },
    adress: {
      title: "حدد عنوانك",
      commune: "عنوانك",
      pOCommune: "البلدية , دائرة",
      wilaya: "حدد ولايتك",
      submitBtn: "إرسال",
    },
    profilContact: {
      title: "معلومات الاتصال",
      phoneLabel: "رقم هاتفك",
      pOPhone: "(إلزامي) مثال: 0567890123",
      FacebookLabel: "رابط الفيسبوك",
      instagramLabel: "رابط الانستغرام",
      twitterLabel: "رابط تويتر",
      pONR: "(اختياري) ex: https://www.... :مثال",
      submitBtn: "التحقق من صحة",
    },
  };
};