const basicSchema = [
  "title",
  "price",
  "description",
  "adress",
  "phone",
  "email",
  "images",
];
const basicFilter = ["price", "adress"];

const schema = [
  {
    slug: "Service",
    name_en: "services",
    name_fr: "services",
    name_ar: "خدمات",
    schema: basicSchema,
    filter: basicFilter,
  },
  {
    slug: "Formation",
    name_en: "Training",
    name_fr: "Formation",
    name_ar: "تمرين",
    schema: [...basicSchema, "formation_category"], /// demander au client
    filter: [...basicFilter, "formation_category"],
  },
  {
    slug: "Job",
    name_en: "Jobs",
    name_fr: "Emplois",
    name_ar: "وظائف",
    schema: [
      ...basicSchema,
      "sector_work",
      "profession",
      "society",
      "wotk_region",
      "diploma",
      "cv_link",
    ],
    filter: [...basicFilter, "sector_work", "wotk_region", "diploma"],
  },
  {
    slug: "Item_and_Equipment",
    name_en: "items and equipment",
    name_fr: "articles et équipement",
    name_ar: "العناصر والمعدا",
    schema: [...basicSchema, "Mark", "typestate"],
    filter: [...basicFilter, "Mark", "typestate"],
  },
  {
    slug: "Product",
    name_en: "Profucts",
    name_fr: "produits",
    name_ar: "منتجات",
    schema: [...basicSchema, "sector_product"],
    filter: [...basicFilter, "sector_product"],
  },
  {
    slug: "Transport",
    name_en: "Transports",
    name_fr: "Transports",
    name_ar: "المواصلات",
    schema: [...basicSchema, "region", "transport_service", "vehicle"],
    filter: [...basicFilter, "region", "transport_service", "vehicle"],
  },
  {
    slug: "Other",
    name_en: "Other",
    name_fr: "Autres",
    name_ar: "الآخرين",
    schema: basicSchema,
    filter: basicFilter,
  },
];
export default schema;

const sector_work = [
  {
    slug: "public_administration",
    name_en: "public administration",
    name_fr: "administration publique",
    name_ar: "الإدارة العمومية",
  },
  {
    slug: "Agriculture",
    name_en: "Agriculture",
    name_fr: "Agriculture",
    name_ar: "الزراعة",
  },
  {
    slug: "Agri_food",
    name_en: "Agri-food",
    name_fr: "Agroalimentaire",
    name_ar: "Agri-food",
  },
  {
    slug: "automobiles",
    name_en: "automobiles",
    name_fr: "automobiles",
    name_ar: "سيارات",
  },
  {
    slug: "Construction_and_civil_engineering",
    name_en: "Construction and civil engineering",
    name_fr: "BTP et génie civile",
    name_ar: "البناء والهندسة المدنية",
  },
  {
    slug: "chemistry_and_para_chemistry",
    name_en: "chemistry and para-chemistry",
    name_fr: "chimie et para chimie",
    name_ar: "الكيمياء وشبه الكيمياء",
  },
  {
    slug: "trade_distribution",
    name_en: "trade, distribution",
    name_fr: "commerce, distribution",
    name_ar: "تجارة, توزيع",
  },
  {
    slug: "communication_advertising_Media",
    name_en: "communication. advertising, Media",
    name_fr: "communication. publicité, Média",
    name_ar: "الاتصالات. الإعلان, وسائل الإعلام",
  },
  {
    slug: "Cosmetic",
    name_en: "Cosmetic",
    name_fr: "Cosmétique",
    name_ar: "مستحضرات التجميل",
  },
  {
    slug: "E_Commerce",
    name_en: "E-Commerce",
    name_fr: "E-commerce",
    name_ar: "التجارة الإلكترونية",
  },
  {
    slug: "energy_environment",
    name_en: "energy, environment",
    name_fr: "énergie, environnement",
    name_ar: "طاقة, بيئة",
  },
  {
    slug: "Education_training",
    name_en: "Education, training",
    name_fr: "Enseignement, formation",
    name_ar: "تعليم, بالمساعدة",
  },
  {
    slug: "studies_advises_assistance",
    name_en: "studies advises assistance",
    name_fr: "études conseille assistance",
    name_ar: "دراسات التدريب تنصح",
  },
  {
    slug: "industry",
    name_en: "industry",
    name_fr: "industrie",
    name_ar: "صناعة",
  },
  {
    slug: "telecom_computing",
    name_en: "telecom computing",
    name_fr: "informatique télécom",
    name_ar: "الحوسبة عن بعد",
  },
  {
    slug: "leisure_culture_sports",
    name_en: "leisure, culture, sports",
    name_fr: "loisir, culture, sports",
    name_ar: "فراغ, حضار, رياضاته",
  },
  {
    slug: "not_disclosed",
    name_en: "not disclosed",
    name_fr: "non communiqué",
    name_ar: "لم يكشف",
  },
  {
    slug: "health_social",
    name_en: "health, social",
    name_fr: "santé, social",
    name_ar: "الصحة, اجتماعي",
  },
  {
    slug: "business_services",
    name_en: "business services",
    name_fr: "services aux entreprises",
    name_ar: "خدمات الأعمال",
  },
  {
    slug: "headquarters",
    name_en: "headquarters",
    name_fr: "sièges sociaux",
    name_ar: "مقر",
  },
  {
    slug: "subcontracting",
    name_en: "subcontracting",
    name_fr: "Sous traitances",
    name_ar: "التعاقد من الباطن",
  },
  {
    slug: "textiles",
    name_en: "textiles",
    name_fr: "textiles",
    name_ar: "المنسوجات",
  },
  {
    slug: "logistic_transport",
    name_en: "logistic transport",
    name_fr: "transport logistique",
    name_ar: "النقل اللوجستي",
  },
  {
    slug: "wood_stone_metal_leather_work",
    name_en: "wood / stone / metal / leather work",
    name_fr: "travaux du bois/pierres/métaux/cuir",
    name_ar: "أعمال خشبية / حجرية / معدنية / جلدية",
  },
  {
    slug: "others",
    name_en: "others",
    name_fr: "autres",
    name_ar: "الآخرين",
  },
];

const diploma = [
  {
    slug: "none",
    name_en: "none",
    name_fr: "aucun",
    name_ar: "لا أملك",
  },
  {
    slug: "cep",
    name_en: "primary school certificate",
    name_fr: "certificat d'études primaires",
    name_ar: "شهادة المدرسة الابتدائية",
  },
  {
    slug: "bem",
    name_en: "College certificate",
    name_fr: "Brevet des collèges",
    name_ar: "شهادة جامعية",
  },
  {
    slug: "bac",
    name_en: "Bacalaureate",
    name_fr: "Bacalauréat",
    name_ar: "البكالوريا",
  },
  {
    slug: "bt",
    name_en: "Higher technician's certificate",
    name_fr: "Brevet de technicien supérieur",
    name_ar: "شهادة تقني سامي",
  },
  {
    slug: "bts",
    name_en: "Technicien diploma",
    name_fr: "Brevet de technicien",
    name_ar: "دبلوم تقني",
  },
  {
    slug: "licence",
    name_en: "Licence",
    name_fr: "Licence",
    name_ar: "رخصة",
  },
  {
    slug: "master",
    name_en: "Master",
    name_fr: "Master",
    name_ar: "يتقن",
  },
  {
    slug: "doctorat",
    name_en: "Doctorate",
    name_fr: "Doctorat",
    name_ar: "دكتوراه",
  },
  {
    slug: "other",
    name_en: "Other",
    name_fr: "Autre",
    name_ar: "آخر",
  },
];

const sector_product = [
  {
    slug: "Agri_food",
    name_en: "Agri-food",
    name_fr: "Agroalimentaire",
    name_ar: "Agri-food",
  },
  {
    slug: "food",
    name_en: "food",
    name_fr: "alimentaire",
    name_ar: "غذاء",
  },
  {
    slug: "chemistry_and_para_chemistry",
    name_en: "chemistry and para-chemistry",
    name_fr: "chimie et para chimie",
    name_ar: "الكيمياء وشبه الكيمياء",
  },
  {
    slug: "commerce_distribution",
    name_en: "commerce-distribution",
    name_fr: "commerce-distribution",
    name_ar: "التوزيع التجاري",
  },
  {
    slug: "communication_gublicity_Media",
    name_en: "communication.gublicity. Media",
    name_fr: "communication.gublicité. Média",
    name_ar: "communication.g publicity. media",
  },
  {
    slug: "cosmetic",
    name_en: "cosmetic",
    name_fr: "cosmétique",
    name_ar: "مستحضرات التجميل",
  },
  {
    slug: "e_commerce",
    name_en: "e-commerce",
    name_fr: "e-commerce",
    name_ar: "التجارة الإلكترونية",
  },
  {
    slug: "energy_environment",
    name_en: "energy-environment",
    name_fr: "énergie-environnement",
    name_ar: "بيئة الطاقة",
  },
  {
    slug: "industry",
    name_en: "industry",
    name_fr: "industrie",
    name_ar: "صناعة",
  },
  {
    slug: "telecom_computing",
    name_en: "telecom computing",
    name_fr: "informatique télécom",
    name_ar: "الحوسبة عن بعد",
  },
  {
    slug: "leisure_culture_sports",
    name_en: "leisure-culture-sports",
    name_fr: "loisir-culture-sports",
    name_ar: "أوقات الفراغ - الثقافة - الرياضة",
  },
  {
    slug: "not_disclosed",
    name_en: "not disclosed",
    name_fr: "non communiqué",
    name_ar: "لم يكشف",
  },
  {
    slug: "social_health",
    name_en: "social health",
    name_fr: "santé-social",
    name_ar: "الصحة الاجتماعية",
  },
  {
    slug: "business_services",
    name_en: "business services",
    name_fr: "services aux entreprises",
    name_ar: "خدمات الأعمال",
  },
  {
    slug: "textiles",
    name_en: "textiles",
    name_fr: "textiles",
    name_ar: "المنسوجات",
  },
  {
    slug: "woodwork_gjiéces_metals_leather",
    name_en: "woodwork / gjiéces / metals / leather",
    name_fr: "travaux du bois/gjiéces/métaux/cuir",
    name_ar: "الأعمال الخشبية / الجيسيس / المعادن / الجلود",
  },
  {
    slug: "others",
    name_en: "others",
    name_fr: "autres",
    name_ar: "الآخرين",
  },
];

const vehicle = [
  {
    slug: "car",
    name_en: "car",
    name_fr: "voiture",
    name_ar: "السيارات",
  },
  {
    slug: "commercial_car",
    name_en: "commercial car",
    name_fr: "voiture commercial",
    name_ar: "سيارة تجارية",
  },
  {
    slug: "pickup",
    name_en: "pickup",
    name_fr: "pick-up",
    name_ar: "يلتقط",
  },
  {
    slug: "mini_bus",
    name_en: "mini bus",
    name_fr: "mini bus",
    name_ar: "ميني باص",
  },
  {
    slug: "van",
    name_en: "van",
    name_fr: "fourgon",
    name_ar: "سيارة نقل",
  },
  {
    slug: "truck__dump_truck",
    name_en: "truck - dump truck",
    name_fr: "camion - a benne",
    name_ar: "تفريغ شاحنة",
  },
  {
    slug: "truck__refrigerated_truck",
    name_en: "truck - refrigerated truck",
    name_fr: "camion - frigorifique",
    name_ar: "شاحنة مبردة",
  },
  {
    slug: "truck__isothermal",
    name_en: "truck - isothermal",
    name_fr: "camion - isotherme",
    name_ar: "شاحنة - متساوية الحرارة",
  },
  {
    slug: "truck__tanker",
    name_en: "truck - tanker",
    name_fr: "camion - citerne",
    name_ar: "ناقلة",
  },
  {
    slug: "truck__bucket_truck",
    name_en: "truck - bucket truck",
    name_fr: "camion - nacelle",
    name_ar: "شاحنة دلو",
  },
  {
    slug: "truck__roll_amplifier",
    name_en: "truck - roll amplifier",
    name_fr: "camion - ampli roll",
    name_ar: "مضخم صوت الشاحنة",
  },
  {
    slug: "truck__tow_truck",
    name_en: "truck - tow truck",
    name_fr: "camion - dépanneuse",
    name_ar: "سحب الشاحنة",
  },
  {
    slug: "truck__other",
    name_en: "truck - other",
    name_fr: "camion - autres",
    name_ar: "شاحنة - أخرى",
  },
  {
    slug: "semi_trailer__low_loader",
    name_en: "semi-trailer - low loader",
    name_fr: "semi remorque - surbaissée",
    name_ar: "نصف مقطورة - لودر منخفض",
  },
  {
    slug: "semi_trailer__single",
    name_en: "semi-trailer - single",
    name_fr: "semi remorque - simple",
    name_ar: "نصف مقطورة - مفردة",
  },
  {
    slug: "semi_trailer__container_carrier",
    name_en: "semi-trailer - container carrier",
    name_fr: "semi remorque - porte conteneur",
    name_ar: "نصف مقطورة - حاملة حاويات",
  },
  {
    slug: "semi_trailer__tank",
    name_en: "semi-trailer - tank",
    name_fr: "semi remorque - citerne",
    name_ar: "نصف مقطورة - صهريج",
  },
  {
    slug: "semi_trailer__other",
    name_en: "semi-trailer - other",
    name_fr: "semi remorque - autres",
    name_ar: "نصف مقطورة - أخرى",
  },
  {
    slug: "Tuff_trailer",
    name_en: "Tuff trailer",
    name_fr: "porte-char",
    name_ar: "مقطورة تاف",
  },
  {
    slug: "Machine__loader",
    name_en: "Machine - loader",
    name_fr: "Engin - chargeuse",
    name_ar: "محمل آلة",
  },
  {
    slug: "Machine__mini_loader",
    name_en: "Machine - mini-loader",
    name_fr: "Engin - mini-chargeuse",
    name_ar: "آلة - محمل صغير",
  },
  {
    slug: "Machine__excavator",
    name_en: "Machine - excavator",
    name_fr: "Engin - pelleteuse",
    name_ar: "آلة - حفارة",
  },
  {
    slug: "Machine__backhoe_loader",
    name_en: "Machine - backhoe loader",
    name_fr: "Engin - tractopelle",
    name_ar: "آلة لودر حفار",
  },
  {
    slug: "Machine__bulldozer",
    name_en: "Machine - bulldozer",
    name_fr: "Engin - bulldozer",
    name_ar: "آلة - جرافة",
  },
  {
    slug: "Machine__scraper",
    name_en: "Machine - scraper",
    name_fr: "Engin - décapeuse",
    name_ar: "مكشطة آلة",
  },
  {
    slug: "Machine__steamroller",
    name_en: "Machine - steamroller",
    name_fr: "Engin - rouleau compresseur",
    name_ar: "الآلة البخارية",
  },
  {
    slug: "Machine__dumper",
    name_en: "Machine - dumper",
    name_fr: "Engin - dumper",
    name_ar: "آلة قلابة",
  },
  {
    slug: "Machine__grader",
    name_en: "Machine - grader",
    name_fr: "Engin - niveleuse",
    name_ar: "آلة ممهدة",
  },
  {
    slug: "Gear__others",
    name_en: "Gear - others",
    name_fr: "Engin - autrres",
    name_ar: "معدات - أخرى",
  },
  {
    slug: "agricultural_machinery__tractor",
    name_en: "agricultural machinery - tractor",
    name_fr: "machines agricoles - tracteur",
    name_ar: "الآلات الزراعية - الجرارات",
  },
  {
    slug: "agricultural_machinery__combine_harvester",
    name_en: "agricultural machinery - combine harvester",
    name_fr: "machines agricoles - moissonneuse-batteuse",
    name_ar: "الآلات الزراعية - حصادة",
  },
  {
    slug: "agricultural_machinery__forage_harvester",
    name_en: "agricultural machinery - forage harvester",
    name_fr: "machines agricoles - ensileuse",
    name_ar: "الآلات الزراعية - حصادة الأعلاف",
  },
  {
    slug: "agricultural_machinery__harvester",
    name_en: "agricultural machinery - harvester",
    name_fr: "machines agricoles - récolteuse",
    name_ar: "الآلات الزراعية - حصادة",
  },
  {
    slug: "agricultural_machinery__mower",
    name_en: "agricultural machinery - mower",
    name_fr: "machines agricoles - faucheuse",
    name_ar: "آلة زراعية - جزازة",
  },
  {
    slug: "agricultural_machinery__other",
    name_en: "agricultural machinery - other",
    name_fr: "machines agricoles - autres",
    name_ar: "آلات زراعية - أخرى",
  },
  {
    slug: "others",
    name_en: "others",
    name_fr: "autres",
    name_ar: "الآخرين",
  },
];

const formation_category = [
  {
    slug: "Industry_training",
    name_en: "Industry training",
    name_fr: "Formation industrie",
    name_ar: "تدريب الصناعة",
  },
  {
    slug: "Computer_training",
    name_en: "Computer training",
    name_fr: "Formation Informatique",
    name_ar: "التدريب على استخدام الحاسوب",
  },
  {
    slug: "Mechanical_Hydraulic,_Pneumatic_Training",
    name_en: "Mechanical, Hydraulic, Pneumatic Training",
    name_fr: "Formation Mécanique, Hydraulique, Pneumatique",
    name_ar: "تدريب ميكانيكي,هيدروليكي,هوائي",
  },
  {
    slug: "Language_training",
    name_en: "Language training ",
    name_fr: "Formation linguistique ",
    name_ar: "التدريب على اللغة ",
  },
  {
    slug: "Surface_treatment_training",
    name_en: "Surface treatment training",
    name_fr: "Formation traitement de surface ",
    name_ar: "تدريب المعالجة السطحية",
  },
  {
    slug: "Safety_training",
    name_en: "Safety training",
    name_fr: "Formation Sécurité",
    name_ar: "تدريب على السلامة",
  },
  {
    slug: "Production_training",
    name_en: "Production training",
    name_fr: "Formation Production",
    name_ar: "تدريب الإنتاج",
  },
  {
    slug: "Management_training",
    name_en: "Management training",
    name_fr: "Formation Management",
    name_ar: "تدريب على الإدارة",
  },
  {
    slug: "Engineer_training",
    name_en: "Engineer training",
    name_fr: "Formation Ingénieurs",
    name_ar: "تدريب المهندسين",
  },
  {
    slug: "Logistics_training",
    name_en: "Logistics training",
    name_fr: "Formation Logistique",
    name_ar: "التدريب اللوجستي",
  },
  {
    slug: "Maintenance_training",
    name_en: "Maintenance training",
    name_fr: "Formation Maintenance",
    name_ar: "تدريب الصيانة",
  },
  {
    slug: "Apprenticeship",
    name_en: "Apprenticeship",
    name_fr: "Formation par apprentissage",
    name_ar: "فترة التدريب في المهنة",
  },
  {
    slug: "Electricity_and_Electronics_training",
    name_en: "Electricity and Electronics training",
    name_fr: "Formation Electricité, Electronique",
    name_ar: "تدريب الكهرباء والإلكترونيات",
  },
  {
    slug: "Choice_and_use_of_materials",
    name_en: "Choice and use of materials",
    name_fr: "Choix et utilisation de matériaux",
    name_ar: "اختيار واستخدام المواد",
  },
  {
    slug: "Commercial_training",
    name_en: "Commercial training",
    name_fr: "Formation Commerciale",
    name_ar: "التدريب التجاري",
  },
  {
    slug: "Quality_Control_Training",
    name_en: "Quality Control Training",
    name_fr: "Formation Contrôle Qualité",
    name_ar: "تدريب مراقبة الجودة",
  },
  {
    slug: "Management__Communication_training",
    name_en: "Management / Communication training",
    name_fr: "Formation Management/Communication",
    name_ar: "التدريب على الإدارة / الاتصال",
  },
  {
    slug: "Metrology_training",
    name_en: "Metrology training",
    name_fr: "Formation en Métrologie",
    name_ar: "التدريب على المقاييس",
  },
  {
    slug: "Continuing_Professional_Training",
    name_en: "Continuing / Professional Training",
    name_fr: "Formation Continue / Professionnelle",
    name_ar: "التدريب المهني المستمر",
  },
  {
    slug: "Automation_training",
    name_en: "Automation training",
    name_fr: "Formation Automatismes",
    name_ar: "تدريب الأتمتة",
  },
  {
    slug: "Regulation__Instrumentation_training",
    name_en: "Regulation / Instrumentation training",
    name_fr: "Formation Regulation/Instrumentation",
    name_ar: "التدريب على التنظيم / الأجهزة",
  },
  {
    slug: "Training in_aeraulics_and_ventilation",
    name_en: "Training in aeraulics and ventilation",
    name_fr: "Formation en aéraulique et ventilation",
    name_ar: "التدريب على التهوية الهوائية",
  },
  {
    slug: "Training_in_industrial_acoustics",
    name_en: "Training in industrial acoustics",
    name_fr: "Formation en acoustique industrielle",
    name_ar: "التدريب في الصوتيات الصناعية",
  },
  {
    slug: "Construction_training_Construction__Real_estate",
    name_en: "Construction training - Construction - Real estate",
    name_fr: "Formation BTP - Construction - Immobilier",
    name_ar: "التدريب على البناء - البناء - العقارات",
  },
  {
    slug: "Environmental_training",
    name_en: "Environmental training",
    name_fr: "Formation en Environnement",
    name_ar: "التدريب البيئي",
  },
  {
    slug: "Laboratory_training",
    name_en: "Laboratory training",
    name_fr: "Formation Laboratoire",
    name_ar: "تدريب المختبر",
  },
  {
    slug: "Communication_training",
    name_en: "Communication training",
    name_fr: "Formation Communication",
    name_ar: "تدريب الاتصال",
  },
  {
    slug: "Microengineering_training",
    name_en: "Microengineering training",
    name_fr: "Formation Microtechnique",
    name_ar: "تدريب الهندسة الدقيقة",
  },
  {
    slug: "Scientific_or_Mathematical_Training",
    name_en: "Scientific or Mathematical Training",
    name_fr: "Formation Scientifique ou Mathématiques",
    name_ar: "تدريب علمي أو رياضي",
  },
];

let test = {
 slug:
    [
      "Industrial_buyer",
      "Acoustician",
      "Computer_network_administrator",
      "Maintenance_agent",
      "Logistics_agent",
      "Continuous_improvement_coordinator",
      "Sales_assistant",
      "Executive_assistant",
      "HR_assistant",
      "Electrical_equipment_winder",
      "Forklift_operator",
      "Business_manager",
      "Communication_manager",
      "Boilermaker",
      "Team_leader",
      "Product_manager",
      "Mechanical_project_manager",
      "Coach,_skills_development",
      "Accountant",
      "Production_line_operator",
      "Management_controller",
      "Cleavage",
      "Industrial_designer",
      "Draftsman__designer",
      "Administrative_and_financial_director",
      "Director_of_design_office",
      "Commercial_director",
      "Director_of_company",
      "Production_manager",
      "R&D_director",
      "Human_resources_director",
      "Technical_director",
      "Electrical_technician",
      "Ergonomist",
      "Trainer",
      "Technical_trainer",
      "Milling_machine",
      "Payroll_manager",
      "Hydraulic_engineer",
      "Calculation__simulation_engineer",
      "Test_engineer",
      "Electronic_design_engineer",
      "Production_engineer",
      "Electrical_engineer",
      "Industrial_engineer",
      "Industrial_IT_engineer",
      "Materials_engineer",
      "Methods_engineer",
      "R&D_engineer",
      "Nuclear_safety_and_dismantling_engineer",
      "Systems_engineer",
      "Electronic_production_integrator",
      "Legal_expert",
      "Mechatronics_engineer",
      "Aluminum_carpenter",
      "Metallier_Carpentier",
      "Fitter__assembler",
      "Fitter__cable_worker",
      "Forge_operator",
      "Production_operator",
      "Metal_processing_operator",
      "Foundry_operator",
      "Operator_composite_materials",
      "Surface_treatment_operator",
      "Machining_operator",
      "Toolmaker",
      "Toolmaker",
      "Industrial_painter",
      "Industrial_production_system_pilot",
      "Industrial_polisher",
      "Technical_writer",
      "Communication_manager",
      "Production_unit_manager",
      "Industrial_analysis_laboratory_manager",
      "Training_manager",
      "Industrial_and_logistics_management_manager",
      "HSE_manager",
      "Maintenance_manager",
      "Marketing_manager",
      "Methods_manager",
      "Scheduling_manager",
      "IT_project_manager",
      "Quality_manager",
      "HR_manager",
      "Welder",
      "Test_technician",
      "Industrial_analysis_laboratory_technician",
      "Production_technician",
      "Electronics_test_technician",
      "Information_systems_technician",
      "Automation_technician",
      "Technician_in_design_and_electronic_development",
      "Metrology_technician",
      "Refrigeration_and_air_conditioning_technician",
      "HSE_technician",
      "Industrial_IT_technician",
      "Industrial_equipment_installation_technician",
      "Electronic_installation_and_maintenance_technician",
      "Logistics_technician",
      "Maintenance_technician",
      "Methods_technician",
      "Photonics_technician",
      "Quality_technician",
      "R&D_technician",
      "Customer_support_technician",
      "Surface_treatment_technician",
      "Machining_technician",
      "Sales_technician",
      "Turner",
      "Industrial_pipefitter"
    ],

  en: [
    "Industrial buyer (M / F)",
    "Acoustician (M / F)",
    "Computer network administrator (M / F)",
    "Maintenance agent (M / F)",
    "Logistics agent (M / F)",
    "Continuous improvement coordinator (M / F)",
    "Sales assistant (M / F)",
    "Executive assistant (M / F)",
    "HR assistant",
    "Electrical equipment winder (M / F)",
    "Forklift operator (M / F)",
    "Business manager (M / F)",
    "Communication manager (M / F)",
    "Boilermaker (M / F)",
    "Team leader (M / F)",
    "Product manager (M / F)",
    "Mechanical project manager (M / F)",
    "Coach, skills development M / F",
    "Accountant (M / F)",
    "Production line operator (M / F)",
    "Management controller (M / F)",
    "Cleavage (M / F)",
    "Industrial designer (M / F)",
    "Draftsman - designer (M / F)",
    "Administrative and financial director (M / F)",
    "Director of design office (M / F)",
    "Commercial director (M / F)",
    "Director of company (M / F)",
    "Production manager (M / F)",
    "R&D director (M / F)",
    "Human resources director (M / F)",
    "Technical director (M / F)",
    "Electrical technician (M / F)",
    "Ergonomist (M / F)",
    "Trainer (M / F)",
    "Technical trainer M / F",
    "Milling machine (M / F)",
    "Payroll manager (M / F)",
    "Hydraulic engineer (M / F)",
    "Calculation / simulation engineer (M / F)",
    "Test engineer (M / F)",
    "Electronic design engineer (M / F)",
    "Production engineer (M / F)",
    "Electrical engineer (M / F) F)",
    "Industrial engineer (M / F)",
    "Industrial IT engineer (M / F)",
    "Materials engineer (M / F)",
    "Methods engineer (M / F)",
    "R&D engineer ( M / F)",
    "Nuclear safety and dismantling engineer (M / F)",
    "Systems engineer (M / F)",
    "Electronic production integrator (M / F)",
    "Legal expert (M / F)",
    "Mechatronics engineer (M / F)",
    "Aluminum carpenter (M / F)",
    "Metal worker Carpentier  (M / F)",
    "Fitter - assembler (M / F)",
    "Fitter - cable worker (M / F)",
    "Forge operator (M / F)",
    "Production operator (M / F)",
    "Metal processing operator (M / F)",
    "Foundry operator (M / F)",
    "Operator composite materials (M / F)",
    "Surface treatment operator (M / F)",
    "Machining operator (M / F)",
    "Toolmaker (M / F)",
    "Toolmaker (M / F)",
    "Industrial painter (M / F)",
    "Industrial production system pilot (M / F)",
    "Industrial polisher (M / F)",
    "Technical writer (M / F)",
    "Communication manager (M / F) F)",
    "Production unit manager (M / F)",
    "Industrial analysis laboratory manager (M / F)",
    "Training manager (M / F)",
    "Industrial and logistics management manager ( M / F)",
    "HSE manager (M / F)",
    "Maintenance manager (M / F)",
    "Marketing manager (M / F)",
    "Methods manager (M / F)",
    "Scheduling manager ( M / F)",
    "IT project manager (M / F)",
    "Quality manager (M / F)",
    "HR manager",
    "Welder (M / F)",
    "Test technician (M / F) )",
    "Industrial analysis laboratory technician (M / F)",
    "Production technician (M / F)",
    "Electronics test technician (M / F)",
    "Information systems technician ( M / F)",
    "Automation technician (M / F)",
    "Technician in design and electronic development (M / F)",
    "Metrology technician (M / F)",
    "Refrigeration and air conditioning technician (M / F)",
    "HSE technician (M / F)",
    "Industrial IT technician (M / F)",
    "Industrial equipment installation technician (M / F)",
    "Electronic installation and maintenance technician (M / F)",
    "Logistics technician (M / F)",
    "Maintenance technician (M / F)",
    "Methods technician (M / F)",
    "Photonics technician (M / F)",
    "Quality technician (M / F)",
    "R&D technician (M / F)",
    "Customer support technician (M / F)",
    "Surface treatment technician (M / F)",
    "Machining technician (M / F)",
    "Sales technician (M / F)",
    "Turner (M / F)",
    "Industrial pipefitter (M / F)",
  ],
  fr: [
    "Acheteur industriel (H/F)",
    "Acousticien (H/F)",
    "Administrateur réseau informatique (H/F)",
    "Agent de maintenance (H/F)",
    "Agent logistique (H/F)",
    "Animateur amélioration continue (H/F)",
    "Assistant commercial (H/F)",
    "Assistant de direction (H/F)",
    "Assistant(e) RH",
    "Bobinier en matériel électrique (H/F)",
    "Cariste (H/F)",
    "Chargé d'affaires (H/F)",
    "Chargé de communication (H/F)",
    "Chaudronnier (H/F)",
    "Chef d'équipe (H/F)",
    "Chef de produit (H/F)",
    "Chef de projet mécanique (H/F)",
    "Coach, développement des compétences H/F",
    "Comptable (H/F)",
    "Conducteur de ligne de production (H/F)",
    "Contrôleur de gestion (H/F)",
    "Décolleteur (H/F)",
    "Designer industriel (H/F)",
    "Dessinateur - projeteur (H/F)",
    "Directeur administratif et financier (H/F)",
    "Directeur bureau d'études (H/F)",
    "Directeur commercial (H/F)",
    "Directeur d'entreprise (H/F)",
    "Directeur de production (H/F)",
    "Directeur R&D (H/F)",
    "Directeur ressources humaines (H/F)",
    "Directeur technique (H/F)",
    "Électrotechnicien (H/F)",
    "Ergonome (H/F)",
    "Formateur (H/F)",
    "Formateur technique H/F",
    "Fraiseur (H/F)",
    "Gestionnaire paie (H/F)",
    "Hydraulicien (H/F)",
    "Ingénieur calcul/simulation (H/F)",
    "Ingénieur d'essais (H/F)",
    "Ingénieur d'étude en électronique (H/F)",
    "Ingénieur de production (H/F)",
    "Ingénieur électrotechnicien (H/F)",
    "Ingénieur génie industriel (H/F)",
    "Ingénieur informatique industrielle (H/F)",
    "Ingénieur matériaux (H/F)",
    "Ingénieur méthodes (H/F)",
    "Ingénieur R&D (H/F)",
    "Ingénieur sûreté nucléaire et démantèlement (H/F)",
    "Ingénieur systèmes (H/F)",
    "Intégrateur en production électronique (H/F)",
    "Juriste (H/F)",
    "Mécatronicien (H/F)",
    "Menuisier aluminium (H/F)",
    "Métallier-Charpentier (H/F)",
    "Monteur - assembleur (H/F)",
    "Monteur - câbleur (H/F)",
    "Opérateur de forge (H/F)",
    "Opérateur de production (H/F)",
    "Opérateur de transformation des métaux (H/F)",
    "Opérateur en fonderie (H/F)",
    "Opérateur matériaux composites (H/F)",
    "Opérateur traitement de surface (H/F)",
    "Opérateur usinage (H/F)",
    "Outilleur (H/F)",
    "Outilleur-mouliste (H/F)",
    "Peintre industriel (H/F)",
    "Pilote de système de production industrielle (H/F)",
    "Polisseur industriel (H/F)",
    "Rédacteur technique (H/F)",
    "Responsable communication (H/F)",
    "Responsable d'unité de production (H/F)",
    "Responsable de laboratoire d'analyses industrielles (H/F)",
    "Responsable formation (H/F)",
    "Responsable gestion industrielle et logistique (H/F)",
    "Responsable HSE (H/F)",
    "Responsable maintenance (H/F)",
    "Responsable marketing (H/F)",
    "Responsable méthodes (H/F)",
    "Responsable ordonnancement (H/F)",
    "Responsable projet informatique (H/F)",
    "Responsable qualité (H/F)",
    "Responsable RH",
    "Soudeur (H/F)",
    "Technicien d'essais (H/F)",
    "Technicien de laboratoire d'analyse industrielle (H/F)",
    "Technicien de production (H/F)",
    "Technicien de tests en électronique (H/F)",
    "Technicien des systèmes d'information (H/F)",
    "Technicien en automatismes (H/F)",
    "Technicien en conception d'études et développement électronique (H/F)",
    "Technicien en métrologie (H/F)",
    "Technicien froid et climatisation (H/F)",
    "Technicien HSE (H/F)",
    "Technicien informatique industrielle (H/F)",
    "Technicien installation d'équipements industriels (H/F)",
    "Technicien installation et maintenance électronique (H/F)",
    "Technicien logistique (H/F)",
    "Technicien maintenance (H/F)",
    "Technicien méthodes (H/F)",
    "Technicien photonique (H/F)",
    "Technicien qualité (H/F)",
    "Technicien R&D (H/F)",
    "Technicien support clients (H/F)",
    "Technicien traitement de surface (H/F)",
    "Technicien usinage (H/F)",
    "Technico-commercial (H/F)",
    "Tourneur (H/F)",
    "Tuyauteur industriel (H/F)",
  ],
  ar:[
    "المشتري الصناعي (رجل/امرأة)",
    "اخصائي صوت (رجل/امرأة)",
    "مسؤول شبكة الكمبيوتر (رجل/امرأة)",
    "وكيل صيانة (رجل/امرأة)",
    "وكيل لوجستيات (رجل/امرأة)",
    "منسق التحسين المستمر (رجل/امرأة)",
    "مساعد مبيعات (رجل/امرأة)",
    "مساعد تنفيذي (رجل/امرأة)",
    "مساعد الموارد البشرية",
    "لفافة المعدات الكهربائية (رجل/امرأة)",
    "مشغل رافعة شوكية (رجل/امرأة)",
    "القائم بالأعمال (رجل/امرأة)",
    "موظف اتصالات (رجل/امرأة)",
    "صانع الغلايات (رجل/امرأة)",
    "قائد الفريق (رجل/امرأة)",
    "مدير المنتج (رجل/امرأة)",
    "مدير مشروع ميكانيكي (رجل/امرأة)",
    "مدرب, تنمية المهارات رجل/امرأة",
    "محاسب (رجل/امرأة)",
    "مشغل خط الإنتاج (رجل/امرأة)",
    "وحدة تحكم الإدارة (رجل/امرأة)",
    "انقسام (رجل/امرأة)",
    "المصمم الصناعي (رجل/امرأة)",
    "مصمم - مصمم (رجل/امرأة)",
    "المدير الإداري والمالي (رجل/امرأة)",
    "مدير مكتب التصميم (رجل/امرأة)",
    "المدير التجاري (رجل/امرأة)",
    "مدير شركة (رجل/امرأة)",
    "مدير الإنتاج (رجل/امرأة)",
    "مدير البحث والتطوير (رجل/امرأة)",
    "مدير الموارد البشرية (رجل/امرأة)",
    "المدير الفني (رجل/امرأة)",
    "مهندس كهربائي (رجل/امرأة)",
    "عالم بيئة العمل (رجل/امرأة)",
    "مدرب (رجل/امرأة)",
    "المدرب الفني رجل/امرأة",
    "آلة الطحن (رجل/امرأة)",
    "مدير كشوف المرتبات (رجل/امرأة)",
    "مهندس هيدروليكي (رجل/امرأة)",
    "مهندس حساب / محاكاة (رجل/امرأة)",
    "مهندس اختبار (رجل/امرأة)",
    "مهندس في الإلكترونيات (رجل/امرأة)",
    "مهندس إنتاج (رجل/امرأة)",
    "مهندس كهربائي (رجل/امرأة)",
    "مهندس صناعي (رجل/امرأة)",
    "مهندس كمبيوتر صناعي (رجل/امرأة)",
    "مهندس مواد (رجل/امرأة)",
    "مهندس طرق (رجل/امرأة)",
    "R & D مهندس (رجل/امرأة)",
    "مهندس السلامة النووية والتفكيك (رجل/امرأة)",
    "مهندس نظم (رجل/امرأة)",
    "تكامل الإنتاج الإلكتروني (رجل/امرأة)",
    "محام (رجل/امرأة)",
    "مهندس ميكاترونكس (رجل/امرأة)",
    "نجار الألمنيوم (رجل/امرأة)",
    "النجار - النجار (رجل/امرأة)",
    "مُجمِّع - مُجمِّع (رجل/امرأة)",
    "المجمع - cabler (رجل/امرأة)",
    "عامل التشكيل (رجل/امرأة)",
    "مشغل الإنتاج (رجل/امرأة)",
    "مشغل معالجة المعادن (رجل/امرأة)",
    "مشغل المسبك (رجل/امرأة)",
    "مشغل المواد المركبة (رجل/امرأة)",
    "عامل المعالجة السطحية (رجل/امرأة)",
    "مشغل بالقطع (رجل/امرأة)",
    "صانع الأدوات (رجل/امرأة)",
    "صانع الأدواتr (رجل/امرأة)",
    "الرسام الصناعي (رجل/امرأة)",
    "رائد نظام الإنتاج الصناعي (رجل/امرأة)",
    "الملمع الصناعي (رجل/امرأة)",
    "كاتب تقني (رجل/امرأة)",
    "مدير الاتصالات (رجل/امرأة)",
    "رئيس وحدة الإنتاج (رجل/امرأة)",
    "مدير مختبر التحليل الصناعي (رجل/امرأة)",
    "مدير التدريب (رجل/امرأة)",
    "مدير إدارة الصناعة واللوجستيات (رجل/امرأة)",
    "مدير HSE (رجل/امرأة)",
    "مدير الصيانة (رجل/امرأة)",
    "مدير تسويق (رجل/امرأة)",
    "مدير الأساليب (رجل/امرأة)",
    "مدير الجدولة (رجل/امرأة)",
    "مدير مشروع تكنولوجيا المعلومات (رجل/امرأة)",
    "مدير الجودة (رجل/امرأة)",
    "مدير الموارد البشرية",
    "لحام (رجل/امرأة)",
    "فني اختبار (رجل/امرأة)",
    "فني مختبر التحليل الصناعي (رجل/امرأة)",
    "فني إنتاج (رجل/امرأة)",
    "فني اختبار الإلكترونيات (رجل/امرأة)",
    "فني نظم معلومات (رجل/امرأة)",
    "فني أتمتة (رجل/امرأة)",
    "تقني في تصميم الدراسات والتطوير الإلكتروني (رجل/امرأة)",
    "فني المقاييس (رجل/امرأة)",
    "فني تبريد وتكييف (رجل/امرأة)",
    "فني HSE (رجل/امرأة)",
    "فني تكنولوجيا المعلومات الصناعية (رجل/امرأة)",
    "فني تركيب المعدات الصناعية (رجل/امرأة)",
    "فني تركيب وصيانة إلكترونية (رجل/امرأة)",
    "فني لوجستيات (رجل/امرأة)",
    "فني صيانة (رجل/امرأة)",
    "فني طرق (رجل/امرأة)",
    "فني ضوئي (رجل/امرأة)",
    "فني جودة (رجل/امرأة)",
    "فني بحث وتطوير (رجل/امرأة)",
    "فني دعم العملاء (رجل/امرأة)",
    "فني المعالجة السطحية (رجل/امرأة)",
    "فني تصنيع (رجل/امرأة)",
    "مندوب مبيعات تقني (رجل/امرأة)",
    "تيرنر (رجل/امرأة)",
    "مصنع الأنابيب الصناعية (رجل/امرأة)",
  ],
};

let sector = [];
test.slug.map((i, key) => {
  console.log("key", key);
  sector = [
    ...sector,
    {
      slug: i,
      name_en: test.en[key],
      name_fr: test.fr[key],
      name_ar: test.ar[key],
    },
  ];
});
console.log("sector", JSON.stringify(sector));

/*
 */
/*




*/
