const basicSchema = [
  "title",
  "price",
  "description",
  "adress",
  "phone",
  "email",
  "images",
];
const basicFilter = ["q","price", "adress"];

export const schema = [{
    slug: "Service",
    name_en: "services",
    name_fr: "services",
    name_ar: "خدمات",
    schema: [...basicSchema, "service_category"],  
    filter: [...basicFilter, "service_category"],
  },
  {
    slug: "Formation",
    name_en: "Training",
    name_fr: "Formation",
    name_ar: "تمرين",
    schema: [...basicSchema, "formation_category"],  
    filter: [...basicFilter, "formation_category"],
  },
  {
    slug: "Job",
    name_en: "Jobs",
    name_fr: "Emplois",
    name_ar: "وظائف",
    schema: [
      ...basicSchema,
      "sector_work",
      "profession",
      "society",
      "region",
      "diploma",
      "cv_link",
    ],
    filter: [...basicFilter, "sector_work", "region", "diploma"],
  },
  {
    slug: "Item_and_Equipment",
    name_en: "items and equipment",
    name_fr: "articles et équipement",
    name_ar: "العناصر والمعدا",
    schema: [...basicSchema, "Mark", "typestate"],
    filter: [...basicFilter, "Mark", "typestate"],
  },
  {
    slug: "Product",
    name_en: "Profucts",
    name_fr: "produits",
    name_ar: "منتجات",
    schema: [...basicSchema, "sector_product"],
    filter: [...basicFilter, "sector_product"],
  },
  {
    slug: "Transport",
    name_en: "Transports",
    name_fr: "Transports",
    name_ar: "المواصلات",
    schema: [...basicSchema, "region", "transport_service", "vehicle"],
    filter: [...basicFilter, "region", "transport_service", "vehicle"],
  },
  {
    slug: "Divers",
    name_en: "Divers",
    name_fr: "Divers",
    name_ar: "متنوع",
    schema: basicSchema,
    filter: basicFilter,
  },
];

export const work_proposal =[
  {
    slug: "request",
    name_en: "Job application",
    name_fr: "demande d'emploi",
    name_ar: "طلب عمل",
  },  {
    slug: "offer",
    name_en: "job offer",
    name_fr: "offre d'emploi",
    name_ar: "عرض عمل",
  }
]

export const sector_work = [{
    slug: "public_administration",
    name_en: "public administration",
    name_fr: "administration publique",
    name_ar: "الإدارة العمومية",
  },
  {
    slug: "Agriculture",
    name_en: "Agriculture",
    name_fr: "Agriculture",
    name_ar: "الزراعة",
  },
  {
    slug: "Agri_food",
    name_en: "Agri-food",
    name_fr: "Agroalimentaire",
    name_ar: "Agri-food",
  },
  {
    slug: "automobiles",
    name_en: "automobiles",
    name_fr: "automobiles",
    name_ar: "سيارات",
  },
  {
    slug: "Construction_and_civil_engineering",
    name_en: "Construction and civil engineering",
    name_fr: "BTP et génie civile",
    name_ar: "البناء والهندسة المدنية",
  },
  {
    slug: "chemistry_and_para_chemistry",
    name_en: "chemistry and para-chemistry",
    name_fr: "chimie et para chimie",
    name_ar: "الكيمياء وشبه الكيمياء",
  },
  {
    slug: "trade_distribution",
    name_en: "trade, distribution",
    name_fr: "commerce, distribution",
    name_ar: "تجارة, توزيع",
  },
  {
    slug: "communication_advertising_Media",
    name_en: "communication. advertising, Media",
    name_fr: "communication. publicité, Média",
    name_ar: "الاتصالات. الإعلان, وسائل الإعلام",
  },
  {
    slug: "Cosmetic",
    name_en: "Cosmetic",
    name_fr: "Cosmétique",
    name_ar: "مستحضرات التجميل",
  },
  {
    slug: "E_Commerce",
    name_en: "E-Commerce",
    name_fr: "E-commerce",
    name_ar: "التجارة الإلكترونية",
  },
  {
    slug: "energy_environment",
    name_en: "energy, environment",
    name_fr: "énergie, environnement",
    name_ar: "طاقة, بيئة",
  },
  {
    slug: "Education_training",
    name_en: "Education, training",
    name_fr: "Enseignement, formation",
    name_ar: "تعليم, بالمساعدة",
  },
  {
    slug: "studies_advises_assistance",
    name_en: "studies advises assistance",
    name_fr: "études conseille assistance",
    name_ar: "دراسات التدريب تنصح",
  },
  {
    slug: "industry",
    name_en: "industry",
    name_fr: "industrie",
    name_ar: "صناعة",
  },
  {
    slug: "telecom_computing",
    name_en: "telecom computing",
    name_fr: "informatique télécom",
    name_ar: "الحوسبة عن بعد",
  },
  {
    slug: "leisure_culture_sports",
    name_en: "leisure, culture, sports",
    name_fr: "loisir, culture, sports",
    name_ar: "فراغ, حضار, رياضاته",
  },
  {
    slug: "not_disclosed",
    name_en: "not disclosed",
    name_fr: "non communiqué",
    name_ar: "لم يكشف",
  },
  {
    slug: "health_social",
    name_en: "health, social",
    name_fr: "santé, social",
    name_ar: "الصحة, اجتماعي",
  },
  {
    slug: "business_services",
    name_en: "business services",
    name_fr: "services aux entreprises",
    name_ar: "خدمات الأعمال",
  },
  {
    slug: "headquarters",
    name_en: "headquarters",
    name_fr: "sièges sociaux",
    name_ar: "مقر",
  },
  {
    slug: "subcontracting",
    name_en: "subcontracting",
    name_fr: "Sous traitances",
    name_ar: "التعاقد من الباطن",
  },
  {
    slug: "textiles",
    name_en: "textiles",
    name_fr: "textiles",
    name_ar: "المنسوجات",
  },
  {
    slug: "logistic_transport",
    name_en: "logistic transport",
    name_fr: "transport logistique",
    name_ar: "النقل اللوجستي",
  },
  {
    slug: "wood_stone_metal_leather_work",
    name_en: "wood / stone / metal / leather work",
    name_fr: "travaux du bois/pierres/métaux/cuir",
    name_ar: "أعمال خشبية / حجرية / معدنية / جلدية",
  },
  {
    slug: "others",
    name_en: "others",
    name_fr: "autres",
    name_ar: "الآخرين",
  },
];

export const diploma = [{
    slug: "none",
    name_en: "none",
    name_fr: "aucun",
    name_ar: "لا أملك",
  },
  {
    slug: "cep",
    name_en: "primary school certificate",
    name_fr: "certificat d'études primaires",
    name_ar: "شهادة المدرسة الابتدائية",
  },
  {
    slug: "bem",
    name_en: "College certificate",
    name_fr: "Brevet des collèges",
    name_ar: "شهادة جامعية",
  },
  {
    slug: "bac",
    name_en: "Bacalaureate",
    name_fr: "Bacalauréat",
    name_ar: "البكالوريا",
  },
  {
    slug: "bt",
    name_en: "Technicien diploma",
    name_fr: "Brevet de technicien",
    name_ar: "دبلوم تقني",
  },
  {
    slug: "bts",
    name_en: "Higher technician's certificate",
    name_fr: "Brevet de technicien supérieur",
    name_ar: "شهادة تقني سامي",
  },
  {
    slug: "licence",
    name_en: "Licence",
    name_fr: "Licence",
    name_ar: "رخصة",
  },
  {
    slug: "master",
    name_en: "Master",
    name_fr: "Master",
    name_ar: "يتقن",
  },
  {
    slug: "doctorat",
    name_en: "Doctorate",
    name_fr: "Doctorat",
    name_ar: "دكتوراه",
  },
  {
    slug: "other",
    name_en: "Other",
    name_fr: "Autre",
    name_ar: "آخر",
  },
];

export const sector_product = [{
    slug: "Agri_food",
    name_en: "Agri-food",
    name_fr: "Agroalimentaire",
    name_ar: "Agri-food",
  },
  {
    slug: "food",
    name_en: "food",
    name_fr: "alimentaire",
    name_ar: "غذاء",
  },
  {
    slug: "chemistry_and_para_chemistry",
    name_en: "chemistry and para-chemistry",
    name_fr: "chimie et para chimie",
    name_ar: "الكيمياء وشبه الكيمياء",
  },
  {
    slug: "commerce_distribution",
    name_en: "commerce-distribution",
    name_fr: "commerce-distribution",
    name_ar: "التوزيع التجاري",
  },
  {
    slug: "communication_gublicity_Media",
    name_en: "communication.gublicity. Media",
    name_fr: "communication.gublicité. Média",
    name_ar: "communication.g publicity. media",
  },
  {
    slug: "cosmetic",
    name_en: "cosmetic",
    name_fr: "cosmétique",
    name_ar: "مستحضرات التجميل",
  },
  {
    slug: "e_commerce",
    name_en: "e-commerce",
    name_fr: "e-commerce",
    name_ar: "التجارة الإلكترونية",
  },
  {
    slug: "energy_environment",
    name_en: "energy-environment",
    name_fr: "énergie-environnement",
    name_ar: "بيئة الطاقة",
  },
  {
    slug: "industry",
    name_en: "industry",
    name_fr: "industrie",
    name_ar: "صناعة",
  },
  {
    slug: "telecom_computing",
    name_en: "telecom computing",
    name_fr: "informatique télécom",
    name_ar: "الحوسبة عن بعد",
  },
  {
    slug: "leisure_culture_sports",
    name_en: "leisure-culture-sports",
    name_fr: "loisir-culture-sports",
    name_ar: "أوقات الفراغ - الثقافة - الرياضة",
  },
  {
    slug: "not_disclosed",
    name_en: "not disclosed",
    name_fr: "non communiqué",
    name_ar: "لم يكشف",
  },
  {
    slug: "social_health",
    name_en: "social health",
    name_fr: "santé-social",
    name_ar: "الصحة الاجتماعية",
  },
  {
    slug: "business_services",
    name_en: "business services",
    name_fr: "services aux entreprises",
    name_ar: "خدمات الأعمال",
  },
  {
    slug: "textiles",
    name_en: "textiles",
    name_fr: "textiles",
    name_ar: "المنسوجات",
  },
  {
    slug: "woodwork_gjieces_metals_leather",
    name_en: "woodwork / gjiéces / metals / leather",
    name_fr: "travaux du bois/gjiéces/métaux/cuir",
    name_ar: "الأعمال الخشبية / الجيسيس / المعادن / الجلود",
  },
  {
    slug: "others",
    name_en: "others",
    name_fr: "autres",
    name_ar: "الآخرين",
  },
];

export const vehicle = [{
    slug: "car",
    name_en: "car",
    name_fr: "voiture",
    name_ar: "السيارات",
  },
  {
    slug: "commercial_car",
    name_en: "commercial car",
    name_fr: "voiture commercial",
    name_ar: "سيارة تجارية",
  },
  {
    slug: "pickup",
    name_en: "pickup",
    name_fr: "pick-up",
    name_ar: "يلتقط",
  },
  {
    slug: "mini_bus",
    name_en: "mini bus",
    name_fr: "mini bus",
    name_ar: "ميني باص",
  },
  {
    slug: "van",
    name_en: "van",
    name_fr: "fourgon",
    name_ar: "سيارة نقل",
  },
  {
    slug: "truck__dump_truck",
    name_en: "truck - dump truck",
    name_fr: "camion - a benne",
    name_ar: "تفريغ شاحنة",
  },
  {
    slug: "truck__refrigerated_truck",
    name_en: "truck - refrigerated truck",
    name_fr: "camion - frigorifique",
    name_ar: "شاحنة مبردة",
  },
  {
    slug: "truck__isothermal",
    name_en: "truck - isothermal",
    name_fr: "camion - isotherme",
    name_ar: "شاحنة - متساوية الحرارة",
  },
  {
    slug: "truck__tanker",
    name_en: "truck - tanker",
    name_fr: "camion - citerne",
    name_ar: "ناقلة",
  },
  {
    slug: "truck__bucket_truck",
    name_en: "truck - bucket truck",
    name_fr: "camion - nacelle",
    name_ar: "شاحنة دلو",
  },
  {
    slug: "truck__roll_amplifier",
    name_en: "truck - roll amplifier",
    name_fr: "camion - ampli roll",
    name_ar: "مضخم صوت الشاحنة",
  },
  {
    slug: "truck__tow_truck",
    name_en: "truck - tow truck",
    name_fr: "camion - dépanneuse",
    name_ar: "سحب الشاحنة",
  },
  {
    slug: "truck__other",
    name_en: "truck - other",
    name_fr: "camion - autres",
    name_ar: "شاحنة - أخرى",
  },
  {
    slug: "semi_trailer__low_loader",
    name_en: "semi-trailer - low loader",
    name_fr: "semi remorque - surbaissée",
    name_ar: "نصف مقطورة - لودر منخفض",
  },
  {
    slug: "semi_trailer__single",
    name_en: "semi-trailer - single",
    name_fr: "semi remorque - simple",
    name_ar: "نصف مقطورة - مفردة",
  },
  {
    slug: "semi_trailer__container_carrier",
    name_en: "semi-trailer - container carrier",
    name_fr: "semi remorque - porte conteneur",
    name_ar: "نصف مقطورة - حاملة حاويات",
  },
  {
    slug: "semi_trailer__tank",
    name_en: "semi-trailer - tank",
    name_fr: "semi remorque - citerne",
    name_ar: "نصف مقطورة - صهريج",
  },
  {
    slug: "semi_trailer__other",
    name_en: "semi-trailer - other",
    name_fr: "semi remorque - autres",
    name_ar: "نصف مقطورة - أخرى",
  },
  {
    slug: "Tuff_trailer",
    name_en: "Tuff trailer",
    name_fr: "porte-char",
    name_ar: "مقطورة تاف",
  },
  {
    slug: "Machine__loader",
    name_en: "Machine - loader",
    name_fr: "Engin - chargeuse",
    name_ar: "محمل آلة",
  },
  {
    slug: "Machine__mini_loader",
    name_en: "Machine - mini-loader",
    name_fr: "Engin - mini-chargeuse",
    name_ar: "آلة - محمل صغير",
  },
  {
    slug: "Machine__excavator",
    name_en: "Machine - excavator",
    name_fr: "Engin - pelleteuse",
    name_ar: "آلة - حفارة",
  },
  {
    slug: "Machine__backhoe_loader",
    name_en: "Machine - backhoe loader",
    name_fr: "Engin - tractopelle",
    name_ar: "آلة لودر حفار",
  },
  {
    slug: "Machine__bulldozer",
    name_en: "Machine - bulldozer",
    name_fr: "Engin - bulldozer",
    name_ar: "آلة - جرافة",
  },
  {
    slug: "Machine__scraper",
    name_en: "Machine - scraper",
    name_fr: "Engin - décapeuse",
    name_ar: "مكشطة آلة",
  },
  {
    slug: "Machine__steamroller",
    name_en: "Machine - steamroller",
    name_fr: "Engin - rouleau compresseur",
    name_ar: "الآلة البخارية",
  },
  {
    slug: "Machine__dumper",
    name_en: "Machine - dumper",
    name_fr: "Engin - dumper",
    name_ar: "آلة قلابة",
  },
  {
    slug: "Machine__grader",
    name_en: "Machine - grader",
    name_fr: "Engin - niveleuse",
    name_ar: "آلة ممهدة",
  },
  {
    slug: "Gear__others",
    name_en: "Gear - others",
    name_fr: "Engin - autrres",
    name_ar: "معدات - أخرى",
  },
  {
    slug: "agricultural_machinery__tractor",
    name_en: "agricultural machinery - tractor",
    name_fr: "machines agricoles - tracteur",
    name_ar: "الآلات الزراعية - الجرارات",
  },
  {
    slug: "agricultural_machinery__combine_harvester",
    name_en: "agricultural machinery - combine harvester",
    name_fr: "machines agricoles - moissonneuse-batteuse",
    name_ar: "الآلات الزراعية - حصادة",
  },
  {
    slug: "agricultural_machinery__forage_harvester",
    name_en: "agricultural machinery - forage harvester",
    name_fr: "machines agricoles - ensileuse",
    name_ar: "الآلات الزراعية - حصادة الأعلاف",
  },
  {
    slug: "agricultural_machinery__harvester",
    name_en: "agricultural machinery - harvester",
    name_fr: "machines agricoles - récolteuse",
    name_ar: "الآلات الزراعية - حصادة",
  },
  {
    slug: "agricultural_machinery__mower",
    name_en: "agricultural machinery - mower",
    name_fr: "machines agricoles - faucheuse",
    name_ar: "آلة زراعية - جزازة",
  },
  {
    slug: "agricultural_machinery__other",
    name_en: "agricultural machinery - other",
    name_fr: "machines agricoles - autres",
    name_ar: "آلات زراعية - أخرى",
  },
  {
    slug: "others",
    name_en: "others",
    name_fr: "autres",
    name_ar: "الآخرين",
  },
];

export const formation_category = [{
    slug: "Industry_training",
    name_en: "Industry training",
    name_fr: "Formation industrie",
    name_ar: "تدريب الصناعة",
  },
  {
    slug: "Computer_training",
    name_en: "Computer training",
    name_fr: "Formation Informatique",
    name_ar: "التدريب على استخدام الحاسوب",
  },
  {
    slug: "Mechanical_Hydraulic_Pneumatic_Training",
    name_en: "Mechanical, Hydraulic, Pneumatic Training",
    name_fr: "Formation Mécanique, Hydraulique, Pneumatique",
    name_ar: "تدريب ميكانيكي,هيدروليكي,هوائي",
  },
  {
    slug: "Language_training",
    name_en: "Language training",
    name_fr: "Formation linguistique",
    name_ar: "التدريب على اللغة",
  },
  {
    slug: "Surface_treatment_training",
    name_en: "Surface treatment training",
    name_fr: "Formation traitement de surface ",
    name_ar: "تدريب المعالجة السطحية",
  },
  {
    slug: "Safety_training",
    name_en: "Safety training",
    name_fr: "Formation Sécurité",
    name_ar: "تدريب على السلامة",
  },
  {
    slug: "Production_training",
    name_en: "Production training",
    name_fr: "Formation Production",
    name_ar: "تدريب الإنتاج",
  },
  {
    slug: "Management_training",
    name_en: "Management training",
    name_fr: "Formation Management",
    name_ar: "تدريب على الإدارة",
  },
  {
    slug: "Engineer_training",
    name_en: "Engineer training",
    name_fr: "Formation Ingénieurs",
    name_ar: "تدريب المهندسين",
  },
  {
    slug: "Logistics_training",
    name_en: "Logistics training",
    name_fr: "Formation Logistique",
    name_ar: "التدريب اللوجستي",
  },
  {
    slug: "Maintenance_training",
    name_en: "Maintenance training",
    name_fr: "Formation Maintenance",
    name_ar: "تدريب الصيانة",
  },
  {
    slug: "Apprenticeship",
    name_en: "Apprenticeship",
    name_fr: "Formation par apprentissage",
    name_ar: "فترة التدريب في المهنة",
  },
  {
    slug: "Electricity_and_Electronics_training",
    name_en: "Electricity and Electronics training",
    name_fr: "Formation Electricité, Electronique",
    name_ar: "تدريب الكهرباء والإلكترونيات",
  },
  {
    slug: "Choice_and_use_of_materials",
    name_en: "Choice and use of materials",
    name_fr: "Choix et utilisation de matériaux",
    name_ar: "اختيار واستخدام المواد",
  },
  {
    slug: "Commercial_training",
    name_en: "Commercial training",
    name_fr: "Formation Commerciale",
    name_ar: "التدريب التجاري",
  },
  {
    slug: "Quality_Control_Training",
    name_en: "Quality Control Training",
    name_fr: "Formation Contrôle Qualité",
    name_ar: "تدريب مراقبة الجودة",
  },
  {
    slug: "Management__Communication_training",
    name_en: "Management / Communication training",
    name_fr: "Formation Management/Communication",
    name_ar: "التدريب على الإدارة / الاتصال",
  },
  {
    slug: "Metrology_training",
    name_en: "Metrology training",
    name_fr: "Formation en Métrologie",
    name_ar: "التدريب على المقاييس",
  },
  {
    slug: "Continuing_Professional_Training",
    name_en: "Continuing / Professional Training",
    name_fr: "Formation Continue / Professionnelle",
    name_ar: "التدريب المهني المستمر",
  },
  {
    slug: "Automation_training",
    name_en: "Automation training",
    name_fr: "Formation Automatismes",
    name_ar: "تدريب الأتمتة",
  },
  {
    slug: "Regulation__Instrumentation_training",
    name_en: "Regulation / Instrumentation training",
    name_fr: "Formation Regulation/Instrumentation",
    name_ar: "التدريب على التنظيم / الأجهزة",
  },
  {
    slug: "Training_in_aeraulics_and_ventilation",
    name_en: "Training in aeraulics and ventilation",
    name_fr: "Formation en aéraulique et ventilation",
    name_ar: "التدريب على التهوية الهوائية",
  },
  {
    slug: "Training_in_industrial_acoustics",
    name_en: "Training in industrial acoustics",
    name_fr: "Formation en acoustique industrielle",
    name_ar: "التدريب في الصوتيات الصناعية",
  },
  {
    slug: "Construction_training_Construction__Real_estate",
    name_en: "Construction training - Construction - Real estate",
    name_fr: "Formation BTP - Construction - Immobilier",
    name_ar: "التدريب على البناء - البناء - العقارات",
  },
  {
    slug: "Environmental_training",
    name_en: "Environmental training",
    name_fr: "Formation en Environnement",
    name_ar: "التدريب البيئي",
  },
  {
    slug: "Laboratory_training",
    name_en: "Laboratory training",
    name_fr: "Formation Laboratoire",
    name_ar: "تدريب المختبر",
  },
  {
    slug: "Communication_training",
    name_en: "Communication training",
    name_fr: "Formation Communication",
    name_ar: "تدريب الاتصال",
  },
  {
    slug: "Microengineering_training",
    name_en: "Microengineering training",
    name_fr: "Formation Microtechnique",
    name_ar: "تدريب الهندسة الدقيقة",
  },
  {
    slug: "Scientific_or_Mathematical_Training",
    name_en: "Scientific or Mathematical Training",
    name_fr: "Formation Scientifique ou Mathématiques",
    name_ar: "تدريب علمي أو رياضي",
  },
];

export const profession = [{
    slug: "Industrial_buyer",
    name_en: "Industrial buyer (M / F)",
    name_fr: "Acheteur industriel (H/F)",
    name_ar: "المشتري الصناعي (رجل/امرأة)",
  },
  {
    slug: "Acoustician",
    name_en: "Acoustician (M / F)",
    name_fr: "Acousticien (H/F)",
    name_ar: "اخصائي صوت (رجل/امرأة)",
  },
  {
    slug: "Computer_network_administrator",
    name_en: "Computer network administrator (M / F)",
    name_fr: "Administrateur réseau informatique (H/F)",
    name_ar: "مسؤول شبكة الكمبيوتر (رجل/امرأة)",
  },
  {
    slug: "Maintenance_agent",
    name_en: "Maintenance agent (M / F)",
    name_fr: "Agent de maintenance (H/F)",
    name_ar: "وكيل صيانة (رجل/امرأة)",
  },
  {
    slug: "Logistics_agent",
    name_en: "Logistics agent (M / F)",
    name_fr: "Agent logistique (H/F)",
    name_ar: "وكيل لوجستيات (رجل/امرأة)",
  },
  {
    slug: "Continuous_improvement_coordinator",
    name_en: "Continuous improvement coordinator (M / F)",
    name_fr: "Animateur amélioration continue (H/F)",
    name_ar: "منسق التحسين المستمر (رجل/امرأة)",
  },
  {
    slug: "Sales_assistant",
    name_en: "Sales assistant (M / F)",
    name_fr: "Assistant commercial (H/F)",
    name_ar: "مساعد مبيعات (رجل/امرأة)",
  },
  {
    slug: "Executive_assistant",
    name_en: "Executive assistant (M / F)",
    name_fr: "Assistant de direction (H/F)",
    name_ar: "مساعد تنفيذي (رجل/امرأة)",
  },
  {
    slug: "HR_assistant",
    name_en: "HR assistant",
    name_fr: "Assistant(e) RH",
    name_ar: "مساعد الموارد البشرية",
  },
  {
    slug: "Electrical_equipment_winder",
    name_en: "Electrical equipment winder (M / F)",
    name_fr: "Bobinier en matériel électrique (H/F)",
    name_ar: "لفافة المعدات الكهربائية (رجل/امرأة)",
  },
  {
    slug: "Forklift_operator",
    name_en: "Forklift operator (M / F)",
    name_fr: "Cariste (H/F)",
    name_ar: "مشغل رافعة شوكية (رجل/امرأة)",
  },
  {
    slug: "Business_manager",
    name_en: "Business manager (M / F)",
    name_fr: "Chargé d'affaires (H/F)",
    name_ar: "القائم بالأعمال (رجل/امرأة)",
  },
  {
    slug: "Boilermaker",
    name_en: "Boilermaker (M / F)",
    name_fr: "Chaudronnier (H/F)",
    name_ar: "صانع الغلايات (رجل/امرأة)",
  },
  {
    slug: "Team_leader",
    name_en: "Team leader (M / F)",
    name_fr: "Chef d'équipe (H/F)",
    name_ar: "قائد الفريق (رجل/امرأة)",
  },
  {
    slug: "Product_manager",
    name_en: "Product manager (M / F)",
    name_fr: "Chef de produit (H/F)",
    name_ar: "مدير المنتج (رجل/امرأة)",
  },
  {
    slug: "Mechanical_project_manager",
    name_en: "Mechanical project manager (M / F)",
    name_fr: "Chef de projet mécanique (H/F)",
    name_ar: "مدير مشروع ميكانيكي (رجل/امرأة)",
  },
  {
    slug: "Coach_skills_development",
    name_en: "Coach, skills development M / F",
    name_fr: "Coach, développement des compétences H/F",
    name_ar: "مدرب, تنمية المهارات رجل/امرأة",
  },
  {
    slug: "Accountant",
    name_en: "Accountant (M / F)",
    name_fr: "Comptable (H/F)",
    name_ar: "محاسب (رجل/امرأة)",
  },
  {
    slug: "Production_line_operator",
    name_en: "Production line operator (M / F)",
    name_fr: "Conducteur de ligne de production (H/F)",
    name_ar: "مشغل خط الإنتاج (رجل/امرأة)",
  },
  {
    slug: "Management_controller",
    name_en: "Management controller (M / F)",
    name_fr: "Contrôleur de gestion (H/F)",
    name_ar: "وحدة تحكم الإدارة (رجل/امرأة)",
  },
  {
    slug: "Cleavage",
    name_en: "Cleavage (M / F)",
    name_fr: "Décolleteur (H/F)",
    name_ar: "انقسام (رجل/امرأة)",
  },
  {
    slug: "Industrial_designer",
    name_en: "Industrial designer (M / F)",
    name_fr: "Designer industriel (H/F)",
    name_ar: "المصمم الصناعي (رجل/امرأة)",
  },
  {
    slug: "Draftsman__designer",
    name_en: "Draftsman - designer (M / F)",
    name_fr: "Dessinateur - projeteur (H/F)",
    name_ar: "مصمم - مصمم (رجل/امرأة)",
  },
  {
    slug: "Administrative_and_financial_director",
    name_en: "Administrative and financial director (M / F)",
    name_fr: "Directeur administratif et financier (H/F)",
    name_ar: "المدير الإداري والمالي (رجل/امرأة)",
  },
  {
    slug: "Director_of_design_office",
    name_en: "Director of design office (M / F)",
    name_fr: "Directeur bureau d'études (H/F)",
    name_ar: "مدير مكتب التصميم (رجل/امرأة)",
  },
  {
    slug: "Commercial_director",
    name_en: "Commercial director (M / F)",
    name_fr: "Directeur commercial (H/F)",
    name_ar: "المدير التجاري (رجل/امرأة)",
  },
  {
    slug: "Director_of_company",
    name_en: "Director of company (M / F)",
    name_fr: "Directeur d'entreprise (H/F)",
    name_ar: "مدير شركة (رجل/امرأة)",
  },
  {
    slug: "Production_manager",
    name_en: "Production manager (M / F)",
    name_fr: "Directeur de production (H/F)",
    name_ar: "مدير الإنتاج (رجل/امرأة)",
  },
  {
    slug: "R_D_director",
    name_en: "R&D director (M / F)",
    name_fr: "Directeur R&D (H/F)",
    name_ar: "مدير البحث والتطوير (رجل/امرأة)",
  },
  {
    slug: "Human_resources_director",
    name_en: "Human resources director (M / F)",
    name_fr: "Directeur ressources humaines (H/F)",
    name_ar: "مدير الموارد البشرية (رجل/امرأة)",
  },
  {
    slug: "Technical_director",
    name_en: "Technical director (M / F)",
    name_fr: "Directeur technique (H/F)",
    name_ar: "المدير الفني (رجل/امرأة)",
  },
  {
    slug: "Electrical_technician",
    name_en: "Electrical technician (M / F)",
    name_fr: "Électrotechnicien (H/F)",
    name_ar: "مهندس كهربائي (رجل/امرأة)",
  },
  {
    slug: "Ergonomist",
    name_en: "Ergonomist (M / F)",
    name_fr: "Ergonome (H/F)",
    name_ar: "عالم بيئة العمل (رجل/امرأة)",
  },
  {
    slug: "Trainer",
    name_en: "Trainer (M / F)",
    name_fr: "Formateur (H/F)",
    name_ar: "مدرب (رجل/امرأة)",
  },
  {
    slug: "Technical_trainer",
    name_en: "Technical trainer M / F",
    name_fr: "Formateur technique H/F",
    name_ar: "المدرب الفني رجل/امرأة",
  },
  {
    slug: "Milling_machine",
    name_en: "Milling machine (M / F)",
    name_fr: "Fraiseur (H/F)",
    name_ar: "آلة الطحن (رجل/امرأة)",
  },
  {
    slug: "Payroll_manager",
    name_en: "Payroll manager (M / F)",
    name_fr: "Gestionnaire paie (H/F)",
    name_ar: "مدير كشوف المرتبات (رجل/امرأة)",
  },
  {
    slug: "Hydraulic_engineer",
    name_en: "Hydraulic engineer (M / F)",
    name_fr: "Hydraulicien (H/F)",
    name_ar: "مهندس هيدروليكي (رجل/امرأة)",
  },
  {
    slug: "Calculation__simulation_engineer",
    name_en: "Calculation / simulation engineer (M / F)",
    name_fr: "Ingénieur calcul/simulation (H/F)",
    name_ar: "مهندس حساب / محاكاة (رجل/امرأة)",
  },
  {
    slug: "Test_engineer",
    name_en: "Test engineer (M / F)",
    name_fr: "Ingénieur d'essais (H/F)",
    name_ar: "مهندس اختبار (رجل/امرأة)",
  },
  {
    slug: "Electronic_design_engineer",
    name_en: "Electronic design engineer (M / F)",
    name_fr: "Ingénieur d'étude en électronique (H/F)",
    name_ar: "مهندس في الإلكترونيات (رجل/امرأة)",
  },
  {
    slug: "Production_engineer",
    name_en: "Production engineer (M / F)",
    name_fr: "Ingénieur de production (H/F)",
    name_ar: "مهندس إنتاج (رجل/امرأة)",
  },
  {
    slug: "Electrical_engineer",
    name_en: "Electrical engineer (M / F) F)",
    name_fr: "Ingénieur électrotechnicien (H/F)",
    name_ar: "مهندس كهربائي (رجل/امرأة)",
  },
  {
    slug: "Industrial_engineer",
    name_en: "Industrial engineer (M / F)",
    name_fr: "Ingénieur génie industriel (H/F)",
    name_ar: "مهندس صناعي (رجل/امرأة)",
  },
  {
    slug: "Industrial_IT_engineer",
    name_en: "Industrial IT engineer (M / F)",
    name_fr: "Ingénieur informatique industrielle (H/F)",
    name_ar: "مهندس كمبيوتر صناعي (رجل/امرأة)",
  },
  {
    slug: "Materials_engineer",
    name_en: "Materials engineer (M / F)",
    name_fr: "Ingénieur matériaux (H/F)",
    name_ar: "مهندس مواد (رجل/امرأة)",
  },
  {
    slug: "Methods_engineer",
    name_en: "Methods engineer (M / F)",
    name_fr: "Ingénieur méthodes (H/F)",
    name_ar: "مهندس طرق (رجل/امرأة)",
  },
  {
    slug: "R_D_engineer",
    name_en: "R&D engineer ( M / F)",
    name_fr: "Ingénieur R&D (H/F)",
    name_ar: "R & D مهندس (رجل/امرأة)",
  },
  {
    slug: "Nuclear_safety_and_dismantling_engineer",
    name_en: "Nuclear safety and dismantling engineer (M / F)",
    name_fr: "Ingénieur sûreté nucléaire et démantèlement (H/F)",
    name_ar: "مهندس السلامة النووية والتفكيك (رجل/امرأة)",
  },
  {
    slug: "Systems_engineer",
    name_en: "Systems engineer (M / F)",
    name_fr: "Ingénieur systèmes (H/F)",
    name_ar: "مهندس نظم (رجل/امرأة)",
  },
  {
    slug: "Electronic_production_integrator",
    name_en: "Electronic production integrator (M / F)",
    name_fr: "Intégrateur en production électronique (H/F)",
    name_ar: "تكامل الإنتاج الإلكتروني (رجل/امرأة)",
  },
  {
    slug: "Legal_expert",
    name_en: "Legal expert (M / F)",
    name_fr: "Juriste (H/F)",
    name_ar: "محام (رجل/امرأة)",
  },
  {
    slug: "Mechatronics_engineer",
    name_en: "Mechatronics engineer (M / F)",
    name_fr: "Mécatronicien (H/F)",
    name_ar: "مهندس ميكاترونكس (رجل/امرأة)",
  },
  {
    slug: "Aluminum_carpenter",
    name_en: "Aluminum carpenter (M / F)",
    name_fr: "Menuisier aluminium (H/F)",
    name_ar: "نجار الألمنيوم (رجل/امرأة)",
  },
  {
    slug: "Metallier_Carpentier",
    name_en: "Metal worker Carpentier  (M / F)",
    name_fr: "Métallier-Charpentier (H/F)",
    name_ar: "النجار - النجار (رجل/امرأة)",
  },
  {
    slug: "Fitter__assembler",
    name_en: "Fitter - assembler (M / F)",
    name_fr: "Monteur - assembleur (H/F)",
    name_ar: "مُجمِّع - مُجمِّع (رجل/امرأة)",
  },
  {
    slug: "Fitter__cable_worker",
    name_en: "Fitter - cable worker (M / F)",
    name_fr: "Monteur - câbleur (H/F)",
    name_ar: "المجمع - cabler (رجل/امرأة)",
  },
  {
    slug: "Forge_operator",
    name_en: "Forge operator (M / F)",
    name_fr: "Opérateur de forge (H/F)",
    name_ar: "عامل التشكيل (رجل/امرأة)",
  },
  {
    slug: "Production_operator",
    name_en: "Production operator (M / F)",
    name_fr: "Opérateur de production (H/F)",
    name_ar: "مشغل الإنتاج (رجل/امرأة)",
  },
  {
    slug: "Metal_processing_operator",
    name_en: "Metal processing operator (M / F)",
    name_fr: "Opérateur de transformation des métaux (H/F)",
    name_ar: "مشغل معالجة المعادن (رجل/امرأة)",
  },
  {
    slug: "Foundry_operator",
    name_en: "Foundry operator (M / F)",
    name_fr: "Opérateur en fonderie (H/F)",
    name_ar: "مشغل المسبك (رجل/امرأة)",
  },
  {
    slug: "Operator_composite_materials",
    name_en: "Operator composite materials (M / F)",
    name_fr: "Opérateur matériaux composites (H/F)",
    name_ar: "مشغل المواد المركبة (رجل/امرأة)",
  },
  {
    slug: "Surface_treatment_operator",
    name_en: "Surface treatment operator (M / F)",
    name_fr: "Opérateur traitement de surface (H/F)",
    name_ar: "عامل المعالجة السطحية (رجل/امرأة)",
  },
  {
    slug: "Machining_operator",
    name_en: "Machining operator (M / F)",
    name_fr: "Opérateur usinage (H/F)",
    name_ar: "مشغل بالقطع (رجل/امرأة)",
  },
  {
    slug: "Toolmaker",
    name_en: "Toolmaker (M / F)",
    name_fr: "Outilleur (H/F)",
    name_ar: "صانع الأدوات (رجل/امرأة)",
  },
  {
    slug: "Industrial_painter",
    name_en: "Industrial painter (M / F)",
    name_fr: "Peintre industriel (H/F)",
    name_ar: "الرسام الصناعي (رجل/امرأة)",
  },
  {
    slug: "Industrial_production_system_pilot",
    name_en: "Industrial production system pilot (M / F)",
    name_fr: "Pilote de système de production industrielle (H/F)",
    name_ar: "رائد نظام الإنتاج الصناعي (رجل/امرأة)",
  },
  {
    slug: "Industrial_polisher",
    name_en: "Industrial polisher (M / F)",
    name_fr: "Polisseur industriel (H/F)",
    name_ar: "الملمع الصناعي (رجل/امرأة)",
  },
  {
    slug: "Technical_writer",
    name_en: "Technical writer (M / F)",
    name_fr: "Rédacteur technique (H/F)",
    name_ar: "كاتب تقني (رجل/امرأة)",
  },
  {
    slug: "Communication_manager",
    name_en: "Communication manager (M / F) F)",
    name_fr: "Responsable communication (H/F)",
    name_ar: "مدير الاتصالات (رجل/امرأة)",
  },
  {
    slug: "Production_unit_manager",
    name_en: "Production unit manager (M / F)",
    name_fr: "Responsable d'unité de production (H/F)",
    name_ar: "رئيس وحدة الإنتاج (رجل/امرأة)",
  },
  {
    slug: "Industrial_analysis_laboratory_manager",
    name_en: "Industrial analysis laboratory manager (M / F)",
    name_fr: "Responsable de laboratoire d'analyses industrielles (H/F)",
    name_ar: "مدير مختبر التحليل الصناعي (رجل/امرأة)",
  },
  {
    slug: "Training_manager",
    name_en: "Training manager (M / F)",
    name_fr: "Responsable formation (H/F)",
    name_ar: "مدير التدريب (رجل/امرأة)",
  },
  {
    slug: "Industrial_and_logistics_management_manager",
    name_en: "Industrial and logistics management manager ( M / F)",
    name_fr: "Responsable gestion industrielle et logistique (H/F)",
    name_ar: "مدير إدارة الصناعة واللوجستيات (رجل/امرأة)",
  },
  {
    slug: "HSE_manager",
    name_en: "HSE manager (M / F)",
    name_fr: "Responsable HSE (H/F)",
    name_ar: "مدير HSE (رجل/امرأة)",
  },
  {
    slug: "Maintenance_manager",
    name_en: "Maintenance manager (M / F)",
    name_fr: "Responsable maintenance (H/F)",
    name_ar: "مدير الصيانة (رجل/امرأة)",
  },
  {
    slug: "Marketing_manager",
    name_en: "Marketing manager (M / F)",
    name_fr: "Responsable marketing (H/F)",
    name_ar: "مدير تسويق (رجل/امرأة)",
  },
  {
    slug: "Methods_manager",
    name_en: "Methods manager (M / F)",
    name_fr: "Responsable méthodes (H/F)",
    name_ar: "مدير الأساليب (رجل/امرأة)",
  },
  {
    slug: "Scheduling_manager",
    name_en: "Scheduling manager ( M / F)",
    name_fr: "Responsable ordonnancement (H/F)",
    name_ar: "مدير الجدولة (رجل/امرأة)",
  },
  {
    slug: "IT_project_manager",
    name_en: "IT project manager (M / F)",
    name_fr: "Responsable projet informatique (H/F)",
    name_ar: "مدير مشروع تكنولوجيا المعلومات (رجل/امرأة)",
  },
  {
    slug: "Quality_manager",
    name_en: "Quality manager (M / F)",
    name_fr: "Responsable qualité (H/F)",
    name_ar: "مدير الجودة (رجل/امرأة)",
  },
  {
    slug: "HR_manager",
    name_en: "HR manager",
    name_fr: "Responsable RH",
    name_ar: "مدير الموارد البشرية",
  },
  {
    slug: "Welder",
    name_en: "Welder (M / F)",
    name_fr: "Soudeur (H/F)",
    name_ar: "لحام (رجل/امرأة)",
  },
  {
    slug: "Test_technician",
    name_en: "Test technician (M / F) )",
    name_fr: "Technicien d'essais (H/F)",
    name_ar: "فني اختبار (رجل/امرأة)",
  },
  {
    slug: "Industrial_analysis_laboratory_technician",
    name_en: "Industrial analysis laboratory technician (M / F)",
    name_fr: "Technicien de laboratoire d'analyse industrielle (H/F)",
    name_ar: "فني مختبر التحليل الصناعي (رجل/امرأة)",
  },
  {
    slug: "Production_technician",
    name_en: "Production technician (M / F)",
    name_fr: "Technicien de production (H/F)",
    name_ar: "فني إنتاج (رجل/امرأة)",
  },
  {
    slug: "Electronics_test_technician",
    name_en: "Electronics test technician (M / F)",
    name_fr: "Technicien de tests en électronique (H/F)",
    name_ar: "فني اختبار الإلكترونيات (رجل/امرأة)",
  },
  {
    slug: "Information_systems_technician",
    name_en: "Information systems technician ( M / F)",
    name_fr: "Technicien des systèmes d'information (H/F)",
    name_ar: "فني نظم معلومات (رجل/امرأة)",
  },
  {
    slug: "Automation_technician",
    name_en: "Automation technician (M / F)",
    name_fr: "Technicien en automatismes (H/F)",
    name_ar: "فني أتمتة (رجل/امرأة)",
  },
  {
    slug: "Technician_in_design_and_electronic_development",
    name_en: "Technician in design and electronic development (M / F)",
    name_fr: "Technicien en conception d'études et développement électronique (H/F)",
    name_ar: "تقني في تصميم الدراسات والتطوير الإلكتروني (رجل/امرأة)",
  },
  {
    slug: "Metrology_technician",
    name_en: "Metrology technician (M / F)",
    name_fr: "Technicien en métrologie (H/F)",
    name_ar: "فني المقاييس (رجل/امرأة)",
  },
  {
    slug: "Refrigeration_and_air_conditioning_technician",
    name_en: "Refrigeration and air conditioning technician (M / F)",
    name_fr: "Technicien froid et climatisation (H/F)",
    name_ar: "فني تبريد وتكييف (رجل/امرأة)",
  },
  {
    slug: "HSE_technician",
    name_en: "HSE technician (M / F)",
    name_fr: "Technicien HSE (H/F)",
    name_ar: "فني HSE (رجل/امرأة)",
  },
  {
    slug: "Industrial_IT_technician",
    name_en: "Industrial IT technician (M / F)",
    name_fr: "Technicien informatique industrielle (H/F)",
    name_ar: "فني تكنولوجيا المعلومات الصناعية (رجل/امرأة)",
  },
  {
    slug: "Industrial_equipment_installation_technician",
    name_en: "Industrial equipment installation technician (M / F)",
    name_fr: "Technicien installation d'équipements industriels (H/F)",
    name_ar: "فني تركيب المعدات الصناعية (رجل/امرأة)",
  },
  {
    slug: "Electronic_installation_and_maintenance_technician",
    name_en: "Electronic installation and maintenance technician (M / F)",
    name_fr: "Technicien installation et maintenance électronique (H/F)",
    name_ar: "فني تركيب وصيانة إلكترونية (رجل/امرأة)",
  },
  {
    slug: "Logistics_technician",
    name_en: "Logistics technician (M / F)",
    name_fr: "Technicien logistique (H/F)",
    name_ar: "فني لوجستيات (رجل/امرأة)",
  },
  {
    slug: "Maintenance_technician",
    name_en: "Maintenance technician (M / F)",
    name_fr: "Technicien maintenance (H/F)",
    name_ar: "فني صيانة (رجل/امرأة)",
  },
  {
    slug: "Methods_technician",
    name_en: "Methods technician (M / F)",
    name_fr: "Technicien méthodes (H/F)",
    name_ar: "فني طرق (رجل/امرأة)",
  },
  {
    slug: "Photonics_technician",
    name_en: "Photonics technician (M / F)",
    name_fr: "Technicien photonique (H/F)",
    name_ar: "فني ضوئي (رجل/امرأة)",
  },
  {
    slug: "Quality_technician",
    name_en: "Quality technician (M / F)",
    name_fr: "Technicien qualité (H/F)",
    name_ar: "فني جودة (رجل/امرأة)",
  },
  {
    slug: "R_D_technician",
    name_en: "R&D technician (M / F)",
    name_fr: "Technicien R&D (H/F)",
    name_ar: "فني بحث وتطوير (رجل/امرأة)",
  },
  {
    slug: "Customer_support_technician",
    name_en: "Customer support technician (M / F)",
    name_fr: "Technicien support clients (H/F)",
    name_ar: "فني دعم العملاء (رجل/امرأة)",
  },
  {
    slug: "Surface_treatment_technician",
    name_en: "Surface treatment technician (M / F)",
    name_fr: "Technicien traitement de surface (H/F)",
    name_ar: "فني المعالجة السطحية (رجل/امرأة)",
  },
  {
    slug: "Machining_technician",
    name_en: "Machining technician (M / F)",
    name_fr: "Technicien usinage (H/F)",
    name_ar: "فني تصنيع (رجل/امرأة)",
  },
  {
    slug: "Sales_technician",
    name_en: "Sales technician (M / F)",
    name_fr: "Technico-commercial (H/F)",
    name_ar: "مندوب مبيعات تقني (رجل/امرأة)",
  },
  {
    slug: "Turner",
    name_en: "Turner (M / F)",
    name_fr: "Tourneur (H/F)",
    name_ar: "تيرنر (رجل/امرأة)",
  },
  {
    slug: "Industrial_pipefitter",
    name_en: "Industrial pipefitter (M / F)",
    name_fr: "Tuyauteur industriel (H/F)",
    name_ar: "مصنع الأنابيب الصناعية (رجل/امرأة)",
  },
];

export const Mark = [{
    slug: "EDIMETA",
    title: "EDIMETA",
  },
  {
    slug: "HEWLETT_PACKARD",
    title: "HEWLETT PACKARD",
  },
  {
    slug: "EPSON",
    title: "EPSON",
  },
  {
    slug: "CENPAC",
    title: "CENPAC",
  },
  {
    slug: "BROTHER",
    title: "BROTHER",
  },
  {
    slug: "ELBA",
    title: "ELBA",
  },
  {
    slug: "CANON",
    title: "CANON",
  },
  {
    slug: "CEP",
    title: "CEP",
  },
  {
    slug: "KARCHER",
    title: "KARCHER",
  },
  {
    slug: "FELLOWES",
    title: "FELLOWES",
  },
  {
    slug: "AVERY",
    title: "AVERY",
  },
  {
    slug: "DURABLE",
    title: "DURABLE",
  },
  {
    slug: "PILOT",
    title: "PILOT",
  },
  {
    slug: "LOTUS_TORK",
    title: "LOTUS-TORK",
  },
  {
    slug: "BOTT",
    title: "BOTT",
  },
  {
    slug: "OXFORD",
    title: "OXFORD",
  },
  {
    slug: "PENTEL",
    title: "PENTEL",
  },
  {
    slug: "LEXMARK",
    title: "LEXMARK",
  },
  {
    slug: "TRODAT",
    title: "TRODAT",
  },
  {
    slug: "LA_COURONNE",
    title: "LA COURONNE",
  },
  {
    slug: "EDDING",
    title: "EDDING",
  },
  {
    slug: "TRESTON",
    title: "TRESTON",
  },
  {
    slug: "LEITZ",
    title: "LEITZ",
  },
  {
    slug: "OKI",
    title: "OKI",
  },
  {
    slug: "Three_M",
    title: "3M",
  },
  {
    slug: "BIMOS",
    title: "BIMOS",
  },
  {
    slug: "NOBO",
    title: "NOBO",
  },
  {
    slug: "SAMSUNG",
    title: "SAMSUNG",
  },
  {
    slug: "HOLZKRAFT",
    title: "HOLZKRAFT",
  },
  {
    slug: "STABILO",
    title: "STABILO",
  },
  {
    slug: "ESSELTE",
    title: "ESSELTE",
  },
  {
    slug: "TARIFOLD",
    title: "TARIFOLD",
  },
  {
    slug: "DORTHZ",
    title: "DORTHZ",
  },
  {
    slug: "FACOM",
    title: "FACOM",
  },
  {
    slug: "NUMATIC",
    title: "NUMATIC",
  },
  {
    slug: "RICOH",
    title: "RICOH",
  },
  {
    slug: "TENG_TOOLS",
    title: "TENG TOOLS",
  },
  {
    slug: "DREUMEX",
    title: "DREUMEX",
  },
  {
    slug: "FESTOOL",
    title: "FESTOOL",
  },
  {
    slug: "REXEL",
    title: "REXEL",
  },
  {
    slug: "RUBBERMAID",
    title: "RUBBERMAID",
  },
  {
    slug: "DELL",
    title: "DELL",
  },
  {
    slug: "ARDEA",
    title: "ARDÉA",
  },
  {
    slug: "SAFE_TOOL",
    title: "SAFE TOOL",
  },
  {
    slug: "UNILUX",
    title: "UNILUX",
  },
  {
    slug: "VESTIBURO",
    title: "VESTIBURO",
  },
  {
    slug: "SIDAMO",
    title: "SIDAMO",
  },
  {
    slug: "UHU",
    title: "UHU",
  },
  {
    slug: "PLANORGA",
    title: "PLANORGA",
  },
  {
    slug: "VIKAN",
    title: "VIKAN",
  },
  {
    slug: "STAEDTLER",
    title: "STAEDTLER",
  },
  {
    slug: "other",
    title: "other",
  },
];



export const service_category = [{
  "slug": "maintenance_revision",
  "name_en": "maintenance - revision",
  "name_fr": "maintenance - revision",
  "name_ar": "الصيانة - المراجعة"
}, {
  "slug": "maintenance_repair",
  "name_en": "maintenance - repair",
  "name_fr": "maintenance - réparation",
  "name_ar": "الصيانة - الإصلاح"
}, {
  "slug": "installation",
  "name_en": "installation",
  "name_fr": "installation",
  "name_ar": "التثبيت"
}, {
  "slug": "measurements_and_analyzes",
  "name_en": "measurements and analyzes",
  "name_fr": "mesures et analyses",
  "name_ar": "القياسات والتحليلات"
}, {
  "slug": "studies_and_tests",
  "name_en": "studies and tests",
  "name_fr": "études et essais",
  "name_ar": "الدراسات والاختبارات"
}, {
  "slug": "advice _nd_expertise",
  "name_en": "advice and expertise",
  "name_fr": "conseils et expertises",
  "name_ar": "المشورة والخبرة"
}, {
  "slug": "design_research",
  "name_en": "design - research",
  "name_fr": "conception - recherche",
  "name_ar": "التصميم - البحث"
}, {
  "slug": "other",
  "name_en": "other",
  "name_fr": "autres",
  "name_ar": "أخرى"
}]



export const region = [{"slug":"remote","name_en":"remote","name_fr":"à télétravail","name_ar":"العمل عن بعد"},{"slug":"regional","name_en":"regional","name_fr":"régional","name_ar":"إقليمي"},{"slug":"national","name_en":"national","name_fr":"nationale","name_ar":"وطني"}]

export const typestate =[{"slug":"new","name_en":"new","name_fr":"Nouveau","name_ar":"الجديد"},{"slug":"almost_new","name_en":"almost new","name_fr":"presque nouveau","name_ar":"شبه جديد"},{"slug":"second_hand","name_en":"second hand","name_fr":"d'occasion","name_ar":"اليد الثانية"},{"slug":"rental","name_en":"rental","name_fr":"location","name_ar":"تأجير"}]

export const transport_service =  [{"slug":"location","name_en":"location","name_fr":"location","name_ar":"تأجير"},{"slug":"driver","name_en":"driver","name_fr":"conducteur","name_ar":"سائق"},{"slug":"other","name_en":"other","name_fr":"autre","name_ar":"آخر"}]
 