export const fr = () => {
    return {
        header: {
            faq: "FAQ & Aide",
            connect: "Se Connecter",
            sub: "S'inscrir",
            search: "Rechercher",
            lang: "français",
            setting: "paramètres",
            profil: "profil",
            disconnect: "Déconnexion",
        },
        Login: {
            errOccured: "Une erreur c'est produit:",
            TitleConnect: "Connectez vous",
            email: "adresse e-mail",
            pass: "mot de passe",
            passMissed: "mot de passe oublié ?",
            btnConnect: "Connexion",
            titleModalMissendPass: "Réinitialisez votre mot de passe.",
            emailSended: "email envoyé!",
            reset: "Réinitialiser",
            emailNotFound: "cet e-mail n'est pas inscrit sur notre site",

            errIncorrect: "e-mail ou mot de passe incorrecte",
            errBlocked: "Votre compte est banni,",
            errWaiting: "Confirmez votre email ! un lien a été envoyer à",
            errUnknow: "erreur , veuillez réesayer",
            btnResend: "Renvoyer",
        },
        signup: {
            errOccured: "Une erreur c'est produit:",
            TitleSign: "Inscrivez vous",
            email: "adresse e-mail",
            pass: "Mot de passe (min 8 caractères)",
            confirmPass: "Confirmez le mot de passe",
            acceptLabel: "Je reconnait avoir lûs et approuver",
            conditionTerms: "les Condituins et termes de la plateforme",

            username: "Nom d'utilisateur",
            lastname: "Nom",
            firstname: "Prénom",
            passNotIdentique: "les mots de passes ne sont pas indentique",
            resend: "Renvoyer ?",
            errorShortName: "Le nom d'utilisateur, le nom et le prénom doit contenir entre 2 et 30 caractères",
            errorEmailInvalide: "email invalide",
            passShort: "le mot de passe doit contenir au moin : 8 caractàres , une majuscule ,une minuscule et 2 chiffres",
            infoExist: "Les information nom d'utilisateur / email existe déjà",
            successEmailSended: "un email a été envoyer à",
        },
        profil: {
            title: "Profil",
            general: "Géneral",
            security: "Sécurité",
            adress: "Adresse",
            contact: "Contact",
        },
        profilGeneral: {
            title: "éditez vos informations".toUpperCase(),
            username: "Nom d'utilisateur",
            lastname: "Nom",
            firstname: "Prénom",
            placeOlderNames: "entre 3 et 20 caractères",
            selectSexe: "sexe",
            selectBoy: "Homme",
            selectGirl: "Femme",
            dateBirth: "Date de naissence",
            dateBDay: "Jour",
            dateMounth: "Mois",
            dateYear: "Année",
            birth_place: "Lieu de naissence",
            PObirth_place: "commune et département",
            submitBtn: "Valider",
        },
        profilSecurity: {
            title: "Sécurité",
            email: "Votre e-mail",
            pOemail: "exemple@gmail.com",
            submitBtn: "Valider",
        },
        adress: {
            title: "Définissez votre adresse".toUpperCase(),
            commune: "Votre Addresse",
            pOCommune: "Commune , Daïra ",
            wilaya: "Séléctionez votre wilaya",
            submitBtn: "Valider",
        },
        profilContact: {
            title: "Information de Contact",
            phoneLabel: "Votre numéro de téléphone",
            pOPhone: "(obligatoir) ex:0567890123",
            facebookLabel: "URL de votre Facebook",
            pONR: "(Facultatif) ex : https://www....",
            instagramLabel: "URL de votre Instagram",
            twitterLabel: "URL de votre Twitte",
            submitBtn: "Valider",
        },
    };
};