import Head from 'next/head'
 


export default function  Home({date = "heloo",data=[]}){
 
  return (
    <div  >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main  >
    <h1>
    hello : {date}
     </h1>

<pre>

  data : {JSON.stringify(data) }
</pre>
 
    </main>
    </div>
  )
}
 
export async function getStaticProps() {
  const res = await fetch(`https://cless-server.herokuapp.com/api/products`)
  const data = await res.json()

  return {
     
    props: {date : new Date().constructor(), data: data  }, // wil
    // Next.js will attempt to re-generate the page:
    // - When a request comes in
    // - At most once every 10 seconds
    revalidate: 10, // In seconds
  }
}

  