import Header from "../components/header.js"
import Slider from "../components/Slider.js"

import Head from 'next/head'
import styles from '../styles/Home.module.css'

 const Home=()=>{
  return (
    <div>
      <Head>
        <title>SINAA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
 <main className="min-vh-100">
      <Header/> 

<Slider/>

 </main>

    </div>
  )
}

export default Home
